
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class JazzParserSym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int INPUT = 13;
  public static final int PLUS = 2;
  public static final int RPAREN = 8;
  public static final int IDENTIFIER = 12;
  public static final int LPAREN = 7;
  public static final int STRING_LITERAL = 17;
  public static final int EQUALS = 10;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int NUMBER = 11;
  public static final int DIVIDE = 5;
  public static final int MINUS = 3;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int STATEMENT = 16;
  public static final int ASSIGNED = 15;
  public static final int POWER = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "POWER",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "EQUALS",
  "NUMBER",
  "IDENTIFIER",
  "INPUT",
  "PRINT",
  "ASSIGNED",
  "STATEMENT",
  "STRING_LITERAL"
  };
}

